### ISSUE TITLE
Make `tmp_pyfhd` smarter

### ISSUE THREAD

**Issue by JLBLine** [ADACS-Australia/PyFHD#15]
When converting `.sav` files out of FHD to read into PyFHD, a `tmp_pyfhd` folder is created because the `scipy` function we use creates a copy of compressed files. Currently, `tmp_pyfhd` is created where the code is being called from, but this might run out of space. So switch to putting `tmp_pyfhd` into the output directory, which must have space in it otherwise no outputs can be made. Also tack on a time string to the dir name, so multiple instances can be run at once with out interference .

**Comment by JLBLine** [comment]
I think change [82b1c46](https://github.com/ADACS-Australia/PyFHD/commit/82b1c46c3a6ae1ff2a157194e61ab12368fd7149) should have fixed this

**Comment by nicholebarry** [comment]
Tested and worked. Previously, I was running out of space with `tmp_pyfhd` on a full disk. Now, it runs within the output directory where I obviously expect to have space. 

Log file says:
```[nbarry@farnarkle2 pyfhd_nb_data_gd_woden_redo_redo_casa_n13_rescaled]$ grep Writing pyfhd_nb_data_gd_woden_redo_redo_casa_n13_rescaled_2023_01_24_18_23_02.log
        Writing intermediate data products to /fred/oz048/MWA/CODE/FHD/pyfhd_nb_data_gd_woden_redo_redo_casa_n13_rescaled/tmp_pyfhd_2023_01_24_18_23_02

**Comment by JLBLine** [comment]
This has been addressed in merge https://github.com/ADACS-Australia/PyFHD/pull/16 so I'm going to close this issue.
